---
title: "TCGA_Heatmap"
format: html
editor: visual
---

## Set Working directory

```{r setup}
own_path <- "/Users/mathildebechgaard"
knitr::opts_knit$set(root.dir = paste0(own_path, "/group_04_project/data/"))
```

## Load Libraries

```{r}
library(tidyverse)
library(ggplot2)
library(reshape2)
```

## Fetch dataset

```{r}
miRNA_log <- readRDS(paste0(own_path, "/group_04_project/data/miRNA_log.RDS"))
miRNA_top_genes <- readRDS(paste0(own_path, "/group_04_project/data/miRNA_top_genes_stat.RDS"))

mRNA_log <- readRDS(paste0(own_path, "/group_04_project/data/mRNA_log.RDS"))
mRNA_top_genes <- readRDS(paste0(own_path, "/group_04_project/data/mRNA_top_genes_stat.RDS"))
```

## miRNA Heatmap

```{r}
miRNA_top_genes <- head(miRNA_top_genes$miRNA_ID, 20)
miRNA_log <- miRNA_log[rownames(miRNA_log) %in% miRNA_top_genes, ]
miRNA_log <- t(miRNA_log)

ggplot(data = melt(miRNA_log), aes(x = Var2, y = Var1, fill = value)) +
  geom_tile() +
  labs(x = "Genes", y = "Patients", title = "Heatmap of Expression Values") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
```

## mRNA Heatmap

```{r}
mRNA_top_genes <- head(miRNA_top_genes$genes, 20)
mRNA_log <- mRNA_log[rownames(mRNA_log) %in% mRNA_top_genes, ]
mRNA_log <- t(mRNA_log)

ggplot(data = melt(mRNA_log), aes(x = Var2, y = Var1, fill = value)) +
  geom_tile() +
  labs(x = "Genes", y = "Patients", title = "Heatmap of Expression Values") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
```
