---
title: "GSE_data_acquisition"
format: html
editor: visual
---

Data pages :

<https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE39833>

<https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GPL14767>

## Libraries

```{r}
#| echo: false
#| eval: true

library(GEOquery)
library(tidyverse)
```

## Loading data

```{r}
#| echo: true
#| eval: true
#| message: false

gse <- getGEO('GSE39833', GSEMatrix = FALSE)
gpl <- getGEO('GPL14767',GSEMatrix=FALSE)
```

## Making a list GSM lists

```{r}
#| echo: true
#| eval: true
gsmlist = (GSMList(gse))
```

## Extract probe IDs from the platform data

```{r}
#| echo: true
#| eval: true
probesets <- Table(GPLList(gse)[[1]])$ID
```

We found out that for some reason ID,s are not migrated, so we decided to acquire them directly

## ID data table

```{r}
#| echo: true 
#| eval: true  
id_gse <- gpl@dataTable@table
```

## Create a matrix with expression values

```{r}
#| echo: true
#| eval: true
data_raw <- do.call('cbind', lapply(gsmlist, function(x) {
  tab <- Table(x)
  mymatch <- match(probesets, tab$ID_REF)
  return(tab$VALUE[mymatch])
}))
data_raw <- apply(data_raw, 2, function(x) {as.numeric(as.character(x))})
```

## Adding ID to Data

```{r}
#| echo: true
#| eval: true 

data_final <- id_gse |>
  merge(data_raw |> 
        as.data.frame() |> 
        mutate(ID = row_number()) |> 
        select(ID, everything()), by = "ID") |>
        filter(!is.na(`PROBE NAME`)) |>
        select(ID, everything())


```

## Deletion of intermediate files

```{r}
#| echo: true
#| eval: true

remove(gsmlist)
remove(probesets)
remove(id_gse)
remove(data_raw)
remove(gpl)
remove(gse)
```

## Citation

```{r}
citation("GEOquery")
```